### ISSUE TITLE
CosmosDataAvailableStore error handling

### ISSUE THREAD

**Issue by michaelmajgaard** [Energinet-DataHub/geh-post-office#125]
Vi forventer der kommer et idempodency check inden rammer PO. BLOCKED. 

In some cases exceptions are thrown, and in other a bool, indicating success or failure, is returned. 
This should be streamlined.
The bool result is returned all the way up to the DataAvailableInbox function and then discarded.

Undersøg problemet hvor der gemmes korrekt i idempotency men fejler ved DA save.  Hvad kan der gøres, exceptions eller retry, deadletter ?

**Comment by defectiveAi** [comment]
Reference: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Exceptions.md

**Comment by defectiveAi** [comment]
A repository:
- Should not know about Cosmos accounts.
- Should not know about physical table names.
- Should not leak CosmosExceptions out of persistence. Cannot handle it in upper layers anyway.
- Should not cast exeptions as a high-trafic component.
- Should be easy to test and fake.
- Should be easy to replace Container, make it point to a test configuration.
- Should be easy to extend with error handling and retry. (Maybe; error handling can be very unique for each use case.)

Therefore:
- Do not inject CosmosClient and Config.
- Do inject an interface providing access to correct storage container, e.g. IDataAvailableContainer.Container.
- Do catch all expected exceptions for typed APIs.
- Read retry is done by API.
- Write retry on failure must be coded explicitly.
- CosmosClient should be singleton according to docs.

Questions:
- Returntype of bool may not be enough, if we want the domain to be able to handle retry.
	- Do we want IRepositoryResult and IRepositoryResult<T> as return type for all public methods?
