### ISSUE TITLE
[Enabler] Post office is ready to communicate with domains and market

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-post-office#132]

**Comment by Tm1807** [comment]
Performance/Throughput:
For Non-meterdata messages:
0,5 seconds in total from DataHub receives the Peak to the market party receives his message

For meter data messages:
30 seconds in total from DataHub receives the Peak to the market party receives his message

We need to measure the through-put times for messages step by step through the system (gateway, sub-postoffices).

Bundling:
Subpostoffices delivers a ‘weight’ with each notification that messages are available to the market parties.

The post office sums up to an agreed max-weight on CIM XML messages or CIM JASON messages and asks 
First: CIM
Then: Jason
Later: EbiX 


Message-‘BUS’:
Postoffice will create the ‘BUS’ to enable the total messageflow starting from the initial notification from sub-postoffice and to sending the message to the market party.

Create/inform interface to sub-postoffices
