### ISSUE TITLE
Post Office is able to log outbound messages

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#189]
## Problem Description
All communication in and out the Datahub must be logged including all messages in exact form.
This feature is refering to all outgoing communication including the peek and dequeue message
When the message has been saved logged, it must be possible for GUI users based on roles to search and find the message based on specific criterias

### Benefit Hypothesis
In all cases it will be possible to find the basic data which has been the source to an activity in the DataHub

## Acceptance criteria and must have scope
•	The traffic of all channels is logged. B2B and GUI
•	Exact message received and send is stored including rejected messages
•	If feasible old messages (Older than 3 years) can be stored at cold storage 
•	It must be possible to search for all messages independent of domains
	 - Search criteria is attached:   [https://app.zenhub.com/files/337536836/29846062-4720-478e-94f8-f34a9d67b1c4/download](https://app.zenhub.com/files/337536836/29846062-4720-478e-94f8-f34a9d67b1c4/download)
	 - Search function must work across all domains 
•	Confirmation and rejection must be connected to the original message 

##Objectives and key results
What is the revenue impact on our business? Is there a potential penalty or other adverse consequences if we delay?

## Leading Indicators
What is the revenue impact on our business? Is there a potential penalty or other adverse consequences if we delay?

## Non Functional Requirements
GDPR requirements are attached: 
[https://app.zenhub.com/files/337536836/c86c620b-b30f-4786-a6ea-8ff85c9e2094/download](https://app.zenhub.com/files/337536836/c86c620b-b30f-4786-a6ea-8ff85c9e2094/download)

## Stakeholders
Relevant for all teams

## Timeline
End of PI

**Comment by mogensjuul** [comment]
@MartinFHansen @Sondergaard 
Kender i status på denne her.

**Comment by Sondergaard** [comment]
@mogensjuul - jeg har en plan om at mødes med Titans mandag hvor vi gerne skulle lande på et design i fællesskab.

**Comment by mogensjuul** [comment]
Fedt


Closed #189<https://github.com/Energinet-DataHub/geh-post-office/issues/189> as completed.


Venlig hilsen

Mogens Juul Sass-Petersen
Domænearkitekt
DataHub Service
+4524916740
***@***.******@***.***>

Fra: Tm1807 ***@***.***>
Sendt: 8. juni 2022 12:52
Til: Energinet-DataHub/geh-post-office ***@***.***>
Cc: Mogens Juul Sass-Petersen ***@***.***>; State change ***@***.***>
Emne: Re: [Energinet-DataHub/geh-post-office] Post Office is able to log outbound messages (#189)

Vær opmærksom på afsender, links og filer.

Closed #189<https://github.com/Energinet-DataHub/geh-post-office/issues/189> as completed.
