### ISSUE TITLE
Hastighed: Gennemløbstiden på en meddelelse skal kunne måles i de enkelte steps igennem DataHub

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#203]
Performance/Throughput:
For Non-meterdata messages:
0,5 seconds in total from DataHub receives the Peak to the market party receives his message
For meter data messages:
30 seconds in total from DataHub receives the Peak to the market party receives his message

We need to measure the through-put times for messages step by step through the system (gateway, sub-postoffices).

**Comment by xnetsrak** [comment]
@Tm1807  Hvis der skal laves måling på tværs af domæner, er det en mulighed at spørge Microsoft hvordan dette kan gøres. Har talt med BATMAN teamet, og det var denne idé der kom op.

**Comment by Tm1807** [comment]
@xnetsrak Det lyder som en god ide at få Microsoft ind over. Skal jeg å sat noget i gang eller er du/Batman allerede i gang med at række ud?
