### ISSUE TITLE
Flow tegning til Batman

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-post-office#215]

**Comment by MrDach** [comment]
Det ville være fint med et diagram over flow og arkitektur for posthuset, så vi har noget nogenlunde konkret at bygge op i mod.

**Comment by defectiveAi** [comment]
Data Available:
![DataAvailable.png](https://images.zenhubusercontent.com/6107f3c1ffd52d545863a425/2e5a496f-7e61-424b-b0ad-d9ca61c2f893)

Peek:
![Peek.png](https://images.zenhubusercontent.com/6107f3c1ffd52d545863a425/2410d1fc-41e3-46b3-9479-4078fb27d7e5)

Dequeue:
![Dequeue.png](https://images.zenhubusercontent.com/6107f3c1ffd52d545863a425/d6dabfa7-7aa2-429f-bee3-ac936cc51ea5)
