### ISSUE TITLE
Support multiple formats in the outbound postoffice

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/geh-post-office#28]
### Is your feature request related to a problem? Please describe.

We need to be able to support multiple outbound formats. EBIX, CIM and so on.
To do that we will expand the post office with the concept of schemas.

### Describe the solution you'd like.

We will extend the function that peeks with the following functionallity.

1. It will fetch a bundle from cosmos
2. Take the `type` and `version` from the document, and combine that with the query parameter `format`
4. Combine those and look in the schemas storage for any schemas following the type `type/format/version`
5. Map the contents of messages into that format, and content type the query parameter `content-type`
6. Return the message

**Comment by mogensjuul** [comment]
@Renetnielsen included in PI #190
