### ISSUE TITLE
Test tool NuGet package for other domains

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-post-office#336]
**Synopsis**

As the MessageHub domain owner
We want to enable other domains to easily test their integrations with the MessageHub domain
So that they - with a minimum effort - can have good confidence that their integrations are correct

**Acceptance-Criteria**

(Perhaps @defectiveAi has a better suggestion cf. chat in Teams)

Given a .NET MessageHub simulation object is instantiated with a request queue name, a corresponding connection string
And a callback to determine whether to send a bundle request
When invoked with a DataAvailableNotificationDto and the callback confirms to send the bundle request
Then the object sends a bundle request to the queue

**Comment by defectiveAi** [comment]
Suggestion:
```var messageHubSim = new MessageHubSim(connString, "sbq-charges", "sbq-charges-reply", "sbq-charges-dequeue" ...);
messageHubSim.Peek.OnRequest += (data, gln, bundleId) => ... // There is no default logic, so create a simulated bundle however.
messageHubSim.Peek.OnReply += (...) => ... // Investigate the reply and create data, as there is no Blob-storage.
// Simulates incoming data by storing it in memory.
messageHubSim.DataAvailable.InsertSimulationDataAsync(new DataAvailableNotificationDto());
messageHubSim.DataAvailable.InsertSimulationDataAsync(new DataAvailableNotificationDto());
messageHubSim.DataAvailable.InsertSimulationDataAsync(new DataAvailableNotificationDto());
// Invokes OnRequest to create a bundle, then calls the real(?) sbq-charges with that data.
messageHubSim.Peek.PostSimulatedRequestAsync(gln, bundleId);
// Removes simulated data from simulator and calls the real(?) sbq-charges-dequeue with that data.
messageHubSim.Dequeue.PostSimulatedRequestAsync(gln, bundleId);```
