### ISSUE TITLE
Logning: Linked messages

### ISSUE THREAD

**Issue by michaelmajgaard** [Energinet-DataHub/geh-post-office#443]
[Feature](https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/205)

As X I want to be able to include all related messages in a search for a message.

### Questions
- What ties together related messages?

### Accept criteria
- Option to include linked messages in search request

**Comment by ENDK-RHC** [comment]
Her er et eksempel på hvordan det er i dag  i DataHub 2.

Der er indsendt en en anmodning om ændring af målepunkts stamdata.
I svaret er der angivet <ns0:OriginalBusinessDocument>

**Besked ind**

        <MessageContainer>
            <MessageReference>e40b06cd4332451dad38745b355fa7ec</MessageReference>
            <DocumentType>RequestUpdateMasterDataMeteringPoint</DocumentType>
            <MessageType>XML</MessageType>
            <Payload>
                <DK_RequestUpdateMasterDataMeteringPoint xmlns="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3">
                    <HeaderEnergyDocument>
                        <Identification>470c196955a0419caa0d0791547d89e5</Identification>
                        <DocumentType listAgencyIdentifier="260">E58</DocumentType>
                        <Creation>2020-10-22T02:14:32.1998898Z</Creation>
                        <SenderEnergyParty>
                            <Identification schemeAgencyIdentifier="9">5790000683345</Identification>
                        </SenderEnergyParty>
                        <RecipientEnergyParty>
                            <Identification schemeAgencyIdentifier="9">5790001330552</Identification>
                        </RecipientEnergyParty>
                    </HeaderEnergyDocument>
                    <ProcessEnergyContext>
                        <EnergyBusinessProcess listAgencyIdentifier="260">E32</EnergyBusinessProcess>
                        <EnergyBusinessProcessRole listAgencyIdentifier="260">DDM</EnergyBusinessProcessRole>
                        <EnergyIndustryClassification listAgencyIdentifier="6">23</EnergyIndustryClassification>
                    </ProcessEnergyContext>
                    <PayloadMasterDataMPEvent>
                        <MeteringPointDomainLocation>
                            <Identification schemeAgencyIdentifier="9">571313124500225483</Identification>
                        </MeteringPointDomainLocation>
                        <Identification>62b5be6a0171489b8216c4ed25510476</Identification>
                        <DetailMeteringPointCharacteristic>
                            <SettlementMethod listIdentifier="DK" listAgencyIdentifier="260">D01</SettlementMethod>
                            <PhysicalStatusOfMeteringPoint listAgencyIdentifier="260">E22</PhysicalStatusOfMeteringPoint>
                            <TypeOfMeteringPoint listAgencyIdentifier="260">E17</TypeOfMeteringPoint>
                            <SubTypeOfMeteringPoint listIdentifier="DK" listAgencyIdentifier="260">D01</SubTypeOfMeteringPoint>
                            <MeterReadingOccurrence>PT1H</MeterReadingOccurrence>
                            <NetSettlementGroup>0</NetSettlementGroup>
                            <LimitationContractedCapacityCharacteristics>
                                <MaximumCurrent>0</MaximumCurrent>
                            </LimitationContractedCapacityCharacteristics>
                            <MeteringGridAreaUsedDomainLocation>
                                <Identification schemeIdentifier="DK" schemeAgencyIdentifier="260">245</Identification>
                            </MeteringGridAreaUsedDomainLocation>
                            <IncludedProductCharacteristic>
                                <Identification listAgencyIdentifier="9">8716867000030</Identification>
                                <UnitType listAgencyIdentifier="260">KWH</UnitType>
                            </IncludedProductCharacteristic>
                            <DisconnectionType listIdentifier="DK" listAgencyIdentifier="260">D01</DisconnectionType>
                        </DetailMeteringPointCharacteristic>
                        <Occurrence>2020-10-21T22:00:00Z</Occurrence>
                        <InstallationLocationAddress>
                            <StreetName>Overager</StreetName>
                            <StreetCode>1809</StreetCode>
                            <BuildingNumber>33</BuildingNumber>
                            <FloorIdentification />
                            <RoomIdentification />
                            <CitySubDivisionName />
                            <Postcode>7120</Postcode>
                            <CityName>Vejle Øst</CityName>
                            <MunicipalityCode>630</MunicipalityCode>
                            <CountryName>DK</CountryName>
                            <MPAddressWashInstructions listIdentifier="DK" listAgencyIdentifier="260">D01</MPAddressWashInstructions>
                            <DARReference>0a3f50bc-e412-32b8-e044-0003ba298018</DARReference>
                        </InstallationLocationAddress>
                        <MeteringInstallationMeterFacility>
                            <MeterIdentification>10025893</MeterIdentification>
                        </MeteringInstallationMeterFacility>
                        <MeterInstallationMeterCharacteristic>
                            <NumberOfDigits>6.0</NumberOfDigits>
                            <ConversionFactor>1</ConversionFactor>
                            <UnitType listAgencyIdentifier="260">KWH</UnitType>
                            <MeterReadingType listIdentifier="DK" listAgencyIdentifier="260">D01</MeterReadingType>
                        </MeterInstallationMeterCharacteristic>
                    </PayloadMasterDataMPEvent>
                </DK_RequestUpdateMasterDataMeteringPoint>
            </Payload>
        </MessageContainer>

**Svar besked**

<ns0:PayloadChargeEvent>
<ns0:Identification>252ef06e3ce743c5be8d6e853f52c749</ns0:Identification>
<ns0:OriginalBusinessDocument>62b5be6a0171489b8216c4ed25510476</ns0:OriginalBusinessDocument>
<ns0:StatusType listAgencyIdentifier="6">39</ns0:StatusType>
<ns0:MeteringPointDomainLocation>
<ns0:Identification schemeAgencyIdentifier="9">571313124500225483</ns0:Identification>
</ns0:MeteringPointDomainLocation>
</ns0:PayloadChargeEvent>
