### ISSUE TITLE
maintenance & support

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-post-office#563]

**Comment by xnetsrak** [comment]
4 timer: Fejl i parsing af log beskeder gjorde at man ikke kunne fremsøge den. 2 mand på.

**Comment by FirestarJes** [comment]
6 timer, opdateringer til aktør register.

**Comment by FirestarJes** [comment]
1 time opdatering til aktør register

**Comment by defectiveAi** [comment]
15 min, opdatering af skemaer.

**Comment by defectiveAi** [comment]
30 min, opdatering af Guard til .net 6 variation.

**Comment by michaelmajgaard** [comment]
2 timer, erstat deprecated service bus package

**Comment by defectiveAi** [comment]
3 timer, refactor Settings i PostOffice.

**Comment by xnetsrak** [comment]
2 timer, undersøglese af tidsstempel incident for fremsøgning af meddelser

**Comment by mbusk88** [comment]
4 timer: Tilføjelse af nye aktørroller
