### ISSUE TITLE
Examine CIM JSON converter inbound

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#585]
Investigate if it is possible to create a generel converter for all schemes for all domains.

Short answer: No.
Long answer: Yes, but at the cost of high memory consumption/no forward-only-reading.

See comments for more info.

**Comment by defectiveAi** [comment]
Værktøj til at validere Json schemas.

	System.Text.Json (indbygget i .net):
		- Understøtter ikke skemavalidering.

	JsonSchema.NET:
		- Er bygget ovenpå System.Text.Json.
		- Har support for skemavalidering.
		- Ulempe: Er ikke forward-only, kræver hele JsonDocument i hukommelsen.

	Newtonsoft Json.NET Schema:
		- Har support for streaming skemavalidering.
		- Ulempe: Er ikke gratis.

Derudover, så er det ikke muligt at bruge den samme skema validator til både Xml og Json, hvis kravet om forward-only-reading skal gælde for dem begge. Det skyldes at Json validator skal læse hele elementer op i hukommelsen, før den kan afgøre hvordan den skal præsentere dataerne, så de matcher en tilsvarende Xml validator.

Et forsøg på at forklare dette: XmlReader læser starten på et element og derefter alle dens attributter. Efterfølgende er XmlReader klar til at læse indholdet af elementet. I JSON indeholder et element sin værdi i en property med navnet "value". Hvis en hypotetisk JsonReader skulle matche samme traversal af træet som i XmlReader, er den tvunget til at læse igennem alle properties og deres undertræer, indtil den støder på "value" (eller er sikker på den ikke er der). Dette vil dog ikke overholde forward-only-reader kravet.
