### ISSUE TITLE
Refactoring of integration events

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#632]
- [x] Beskrivelse af hvilke events der skal udstilles ( Mikkel & Jesper )
  - Grid Area (XKAMA)
    - [x] (In Main) GridAreaCreated
    - [x] (In Main) GridAreaNameCreated
    - [x] (In Main) Client pakken og parser refactor
    - [x] (In Main) Tests
  - Organization
    - [x] (In Main) OrganizationCreated
    - [x] (In Main) OrganizationNameChanged
    - [x] (In Main) OrganizationAddressChanged
    - [x] (In Main) OrganizationCommentChanged
    - [x] (In Main) OrganizationBusinessRegisterIdentifierChanged
    - [x] (In Main) Client pakken og parser refactor
    - [x] (In Main) Tests
  - Actor
    - [x] (In Main) ActorCreated
    - [x] (In Main) ActorStatusChanged
    - [x] (In Main) ActorRoleAdded
    - [x] (In Main) ActorRoleRemoved
    - [x] (In Main) ActorContactAdded
    - [x] (In Main) ActorContactRemoved
- [x] Event Dokumentation opdateres (efter alle event nu er på plads) ( Mikkel & Jesper )
- [x] Generel dokumentation
- [x] Test specificeres ( alle )

**Comment by mbusk88** [comment]
For at færddiggøre integration events for Actor mangler der følgende...

Integration.Model:
- Alle protobuf kontrakter + parsers.

MarketParticipant:
- Dispatcher metoder for hver type af integrationsevent.
- Test.

**Comment by xnetsrak** [comment]
Alle events skulle være på plads nu.
Opdateret dokumentationsdiagrammer mangler.
