### ISSUE TITLE
Errors in ITLEV environment / Titans

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#650]

**Comment by Tm1807** [comment]
![Fejl i ITLEV miljøet.png](https://images.zenhubusercontent.com/60bdc2fa67611ea75b0f57c0/b56a2a05-a082-4440-8583-f341de072093)

**Comment by Tm1807** [comment]
Nedenstående er et billede over fejl i ITLEV miljøet, Som du kan se i den sorte ramme har Titans de 4 første pladser, er det noget i vil gøre noget ved, og eventuelt lave tests så det ikke sker igen?

**Comment by FirestarJes** [comment]
Det ser ikke ud til at vores peeks fejler mere, vi har en på vores dispatch, men den er jeg igang med at løse
