### ISSUE TITLE
Navn på aktør

### ISSUE THREAD

**Issue by michaelmajgaard** [Energinet-DataHub/geh-post-office#670]
Som bruger har jeg behov for at kunne angive et navn på en aktør.

# Accept criteria
- [x] Ved oprettelse og redigering af en aktør, har jeg mulighed for at angive et navn.
- [x] Testtet ok.
- [x] Ved ændring af navn for en aktør, skal et integrationsevent, som afspejler dette sendes ud.
- [x] Testtet ok.

**Comment by xnetsrak** [comment]
Branch oprettet ud fra den branch med Actor-events - den kan lukkes før denne.
UI er også lavet til frontend.
