### ISSUE TITLE
Redigering af markedsroller når aktør status er andet end 'Ny'

### ISSUE THREAD

**Issue by michaelmajgaard** [Energinet-DataHub/geh-post-office#675]
Som bruger, må jeg ikke kunne slette og ændre i markedsroller, der allerede er oprettet på en aktiv markedsrolle. Det skal dog være muligt at kunne oprette nye markedsroller.

# Accept criteria
- [ ] Det må kun være muligt at fjerne og redigere eksisterende markedsroller for en aktør, hvis aktøren har status 'Ny'.

# Tekniske detaljer
- Skal valideres både backend og frontend.
- Markedsrollerækkerne i UI kan evt. disables, hvis der er tale om en aktiv aktør.

**Comment by ENDK-RHC** [comment]
Testet OK.
