### ISSUE TITLE
Problem med Dequeue ved flere bundles

### ISSUE THREAD

**Issue by FirestarJes** [Energinet-DataHub/geh-post-office#683]
Det kan lade sig gøre via de forskellige endpoints til peek at have flree bundles liggende til samme recipient, når man så forsøger at dequeue den nyeste af dem, får man en fejl da den gamle af dem ikke er dequeued endnu.

Man har desværre så ingen mulighed for at finde ud af hvorfor ens dequeue fejler.

Vi skal have kigget på om:

1. Det skal være muligt at peeke fra to forskellige endpoints og lave to bundles, eller om det er en fejl
2. Om det skal være muligt at dequeue på samme måde med forskellige endpoints.

**Comment by defectiveAi** [comment]
Test with Volt that grid area 806 works correctly.
