### ISSUE TITLE
Ved visningen af meddelelserne: fritekstfelt ønskes til yderligere forfinet søgning på de meddelelser, der fremgik efter 1. søgning

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#709]

**Comment by ENDK-RHC** [comment]
@mimse Jeg kan ikke finde fritekst feltet nogen steder.
Hvor og hvordan finder jeg det.

**Comment by Tm1807** [comment]
Nice to have. De manglende ting er overført til andre tickets. Denne lukkes...
