### ISSUE TITLE
Generelt: Dansk sproglag på indholdet i felterne

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#715]

**Comment by mimse** [comment]
Mangler noget mere info @Tm1807 

Hvilken felter er der tale om?

**Comment by Tm1807** [comment]
Alle felterne :-)
Der er tænkt at man kan skifte mellem sproglagene vha. en knap (engelsk/dansk)

**Comment by mimse** [comment]
Lavet i https://github.com/Energinet-DataHub/geh-post-office/issues/828
