### ISSUE TITLE
Ikon med viskelæder i stedet for 'X Ryd form'

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#716]

**Comment by michaelmajgaard** [comment]
@Tm1807 Har kigget, og vi har ikke et viskelæder-ikon tilgængeligt. Det tætteste vi har derpå, er krydset.

**Comment by Tm1807** [comment]
@michaelmajgaard Ja selvfølgeligt. 'X Ryd form' er det jeg mener med viskelæder.
Tanketorsk. Sorry.

**Comment by Tm1807** [comment]
Ok. Så kører vi med 'X Ryd form'.
Bare luk denne!

**Comment by mimse** [comment]
Løst i https://github.com/Energinet-DataHub/geh-post-office/issues/828
