### ISSUE TITLE
Mulighed for at fremsøge meddelelser på transaktionsID / cim:mRID. Acceptabelt hvis der søges med samme felt som MeddelelsesID

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#718]

**Comment by mimse** [comment]
Er det en af disse felter som er transaktionsId?
![image.png](https://images.zenhubusercontent.com/633fbb34b49ff882a80234ab/433d71f6-4067-4bce-b81f-5f9aa73f3c4b)
Det er lige hvad jeg kan se, som er muligt at søge i

**Comment by xnetsrak** [comment]
mRID er MessageId

**Comment by mimse** [comment]
Efter en snak med @xnetsrak blev vi enige om at det er løst ved at sætte flueben i relaterede beskeder
