### ISSUE TITLE
Net-område

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-post-office#736]
Net-område nummer (ID) (3 karakter alfanumerisk)
 Net-område navn (200 karakter alfanumerisk)

**Comment by ENDK-RHC** [comment]
For at jeg ikke skal bruge meget lang tid på at teste dette vil jeg gerne have at listen er sorteret i Net nummer rækkefølge.

**Comment by ENDK-RHC** [comment]
I udtrækket som Jesper har sendt til mig er NET 115 med.
Net 115 bliver til gengæld ikke vis på listen i GUI.

**Comment by michaelmajgaard** [comment]
@ENDK-RHC Jeg har gennemskuet hvorfor 115 ikke er med i listen, og jeg er ved at lave et fix til det.

**Comment by ENDK-RHC** [comment]
Testet ok.
