### ISSUE TITLE
Volt's test actor in U-001 is not able to peek confirmations for (UpdateChargePrices), while confirmations for (UpdateChargeInformation) can be peeked

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-post-office#741]
**Description:**

Volt's test actor in U-001 is able peek confirmations for (UpdateChargeInformation), but **cannot** peek confirmations for (UpdateChargePrices) 

Note: Batman's test actor is able to peek both in U-001. And it works fine in T-001.

**Data details:**

* **Volt test actor** (id: 08ED22E3-615D-4F0E-993D-CFC1F4A833F8, actorId: A4ABD4AD-4FF3-4E93-A86D-7B164910CA34, gln: 9656626091925)
* **Batman's test actor** (id: "7f7974dd-d2af-460e-8684-cc61f58f8117", actorId: A982DE1F-3703-4E3C-BE56-4E54418A2A59, gln: 0808118335003)
* **PartitionKey** that showed some problem: "facef55d-e842-42c1-92fd-451e2d09d56c"

UpdateChargeInformation is peekable, why UpdateChargePrices is not.

**How to reproduce:** 
(0) Probably the easiest thing is to involve Volt in the reproduction, otherwise :)...
(1) Go to Postman > Charges Domain workspace
(2) Find the following request and use it to create a new subscription: 
Samples/ChargeIngestion/ 'Create Subscription (P1M) without price' => change the mRID used in line 18 to something that does not exist in charges db and submit it.
(3) Find the following request and use it to submit a new price to the newly created subscription
Samples/ChargeIngestion/UpdateChargePrices 'D08 UpdateChargePrices - Subscription - P1M' => remember to same mRID in line 18 as in step (2).
(4) Peek the first time and expect a 'ConfirmRequestChangeOfPriceList' with processType = D18 
(5) Dequeue it and peek again, and expect another 'ConfirmRequestChangeOfPriceList' but this time with processType = D08.
No message is received in step 5 . A HTTP 204 No Content is provided.

**Comment by defectiveAi** [comment]
Volt skriver, at det lader til at virke nu.
