### ISSUE TITLE
Tilføj ForceUpdateActorIntegrationEvents

### ISSUE THREAD

**Issue by FirestarJes** [Energinet-DataHub/geh-post-office#750]
Vi skal have tilføjet en funktion så vi kan force en ActorUpdatedIntegrationEvent for en/flere actors, så vi kan lave manuelle ændringer for at sikre at vi kan give adgang via api kald.

dette er fordi vi ikke automatisk opretter en secret til det id de får når vi opretter dem via GUI på nuværende tidspunkt, og man derfor ikke kan bruge dem. Så lige nu skal man manuelt ind og oprette en aktør i b2c og så skal vi skifte actorId på dem, så man kan bruge dem. Det skal så gerne sendes som et integration Event.

**Comment by xnetsrak** [comment]
Lukkes da vi ikke mener der er behov for denne mere.
