### ISSUE TITLE
netområde aktør / netområde markedsrolle / netområde aktør id

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#753]
### Acceptance Criteria

- [x] netområde aktør / netområde markedsrolle / netområde aktør id

### Testability
- [x] Can be demoed?
- [x] Can be tested?

### Optional Business Notes
- Netområde markedsrolle vises om EIC funktion. Den aktør der vises er den aktør der er tilknyttet som grid access provider
- Organisations ID skal være Aktør ID.

### Optional Techical Notes
- None

**Comment by ENDK-RHC** [comment]
Testet ok.
