### ISSUE TITLE
overgang til fuld flex

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#756]
### Acceptance Criteria

- [x] overgang til fuld flex

### Testability
- [x] Can be demoed?
- [x] Can be tested?

### Optional Business Notes
- Where does 'Fuld Flex' field come from? @Tm1807 

### Optional Techical Notes
- Preload data with (xxx), field is required.

**Comment by ENDK-RHC** [comment]
'Fuld Flex' dato kommer fra DataHub 2 og skal tastet ind eller migreres ind i DataHub 3

**Comment by ENDK-RHC** [comment]
Testet ok
