### ISSUE TITLE
Netområde navn

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#759]
### Acceptance Criteria

- [x] Netområde navn
   - [x] Frontend
   - [x] Backend

### Testability
- [x] Can be demoed?
- [x] Can be tested?

### Optional Business Notes
- None

### Optional Techical Notes
- Ved "gem" vender vi tilbage til visning af det enkelte netområde, som er opdateret.
- Ved "fortryd" vender vi tilbage til visning af det enkelte netområde.

**Comment by ENDK-RHC** [comment]
Redigering af net område navn er testet ok.
