### ISSUE TITLE
Audit log for netområder

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#760]
### Acceptance Criteria

- Log følgende:
  - [x] Bruger id
  - [x] Dato og tidspunkt
  - [x] Navn

### Testability
- [x] Can be demoed?
- [x] Can be tested?

### Optional Business Notes
- None

### Optional Techical Notes
- None

**Comment by ENDK-RHC** [comment]
RHC testet ok
