### ISSUE TITLE
Vis audit log af netområder

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#761]
### Acceptance Criteria

- [x] Dato og tidspunkt for ændring
- [x] Beskrivelse af ændring (brugernavn, feltnavn og fra værdi , til værdi)

### Testability
- [x] Can be demoed?
- [x] Can be tested?

### Optional Business Notes
- None

### Optional Techical Notes
- None

**Comment by ENDK-RHC** [comment]
RHC testet ok
