### ISSUE TITLE
Correct permissions can edit organisations.

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#773]
### Acceptance Criteria

- Only user with correct permissions can edit organisations.

#### Testability
- [x] Can be tested?
- [x] Can be demoed?

### Optional Business Notes
- RHC: See organizations, manage organizations, manage grid areas.
- TML: See organizations, manage actors.

### Optional Techical Notes
- None

**Comment by ENDK-RHC** [comment]
RHC can mange organisations. Test ok

**Comment by Tm1807** [comment]
TML can see organizations, manage actors. Test passed.
