### ISSUE TITLE
[Titans] Roller/rettigheder: 1 Permissions for Organisation view

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#778]
### Description

As a user,
I want to access Organisation view,
when I have the correct permissions

### Acceptance Criteria
- [x] Only user with correct permissions can see organisations.
- [x] Only user with correct permissions can edit organisations.
- [x] Only user with correct permissions can create organisations.
- [x] Only user with correct permissions can see actors.
- [x] Only user with correct permissions can edit actors.
- [x] Only user with correct permissions can create actors.

User is currently a fixed set of users.

### Optional Business Notes
- Changes to permission should happen immediately.

**Comment by Tm1807** [comment]
Skal/kan denne testet inden alle opgaver er løst?
