### ISSUE TITLE
Status 'Slettet' skal ikke være mulig på aktører

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#783]

**Comment by Tm1807** [comment]
Eneste mulige status'er skal være:
Ny
Aktiv
Inaktiv
Passiv

Status 'Slettet' skal... slettes.

**Comment by michaelmajgaard** [comment]
@Tm1807 I følge af din kommentar, kan Passiv kun kan gå til Inaktiv, er det rigtigt? Og i så fald, skal den så ikke også have en warning, da man aldrig kan komme tilbage til Aktiv? I det implementerede vi har i dag, kan Passiv godt gå tilbage til Aktiv.

**Comment by Tm1807** [comment]
@michaelmajgaard Det skrevne er bekræftet af forretningen. Og advarsler ved statusskifte til Passiv og Inaktiv er på sin plads.
Om det så er tekst-warnings eller en nedtælling til dooms-day, der starter - det bestemmer du :-)

**Comment by Tm1807** [comment]
@michaelmajgaard nargh.... vi må nok hellere nøjes med tekst-warnings :-) :-)

**Comment by ENDK-RHC** [comment]
Ændring er testet ok.
