### ISSUE TITLE
Not possible to edit certain actor in frontend - exception thrown

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-post-office#867]
**Observation**
Frontend stalls after clicking 'Edit actor/Rediger aktør' on Organization with Actor Number: 5790000432752

Application insights shows an [exception](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%227b7ffd68-d27e-4c75-936a-2653ecc36450%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-T-001%22%2C%22Name%22%3A%22appi-shared-sharedres-t-001%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7b7ffd68-d27e-4c75-936a-2653ecc36450%252FresourceGroups%252Frg-DataHub-SharedResouces-T-001%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-t-001%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%228dce32cd-542a-11ed-94ee-6045bd9186ff%22%2C%22timestamp%22%3A%222022-10-25T06%3A01%3A19.581Z%22%2C%22cacheId%22%3A%2296484e77-e0e7-4a1f-945a-2f95f1bd452c%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A1800000%2C%22endTime%22%3A%222022-10-25T06%3A03%3A26.004Z%22%7D%7D) was thrown: 

**Environment**
T-001

**Expected result**
After clicking edit actor, it is possible to edit the actor.

**Actual result**
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/78820e82-ce13-443c-9b8b-7d14424c0eab)

**Comment by prtandrup** [comment]
Verified on T-001

**Comment by Tm1807** [comment]
Testet ok af PTA 28-10-2022
