### ISSUE TITLE
Liste over brugerroller - download (nice to have)

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-post-office#972]
Som en bruger ønsker jeg at have muligheden for at downloade listen over roller, og gemme det som en CSV-fil.

- [x] Download knap i card header.
- [x] Flyt paginator til card header.
- [x] Implementer download handler.

**Comment by michaelmajgaard** [comment]
@Tm1807 Er det korrekt, at det er listen af brugerroller, som set herunder, der skal eksporteres som csv?
![image.png](https://images.zenhubusercontent.com/611f82b0c1cf6c71001ee81f/7b06858b-7841-49d4-bf68-c9df575449fc)

**Comment by ENDK-RHC** [comment]
RHC testet ok.
